<?php

namespace Container2YDdIFD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OwMdipHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OwMdipH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OwMdipH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pratiquerRepository' => ['privates', 'App\\Repository\\PratiquerRepository', 'getPratiquerRepositoryService', true],
        ], [
            'pratiquerRepository' => 'App\\Repository\\PratiquerRepository',
        ]);
    }
}
