<?php

namespace Container2YDdIFD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnfantTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EnfantType' shared autowired service.
     *
     * @return \App\Form\EnfantType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\src\\Form\\EnfantType.php';

        return $container->privates['App\\Form\\EnfantType'] = new \App\Form\EnfantType();
    }
}
