<?php

namespace ContainerXfo08RJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1vNbHhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k1vNbHh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k1vNbHh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pratiquer' => ['privates', '.errored..service_locator.k1vNbHh.App\\Entity\\Pratiquer', NULL, 'Cannot autowire service ".service_locator.k1vNbHh": it references class "App\\Entity\\Pratiquer" but no such service exists.'],
        ], [
            'pratiquer' => 'App\\Entity\\Pratiquer',
        ]);
    }
}
