<?php

namespace ContainerXfo08RJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FZfxVaRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FZfxVaR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FZfxVaR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'enfant' => ['privates', '.errored..service_locator.FZfxVaR.App\\Entity\\Enfant', NULL, 'Cannot autowire service ".service_locator.FZfxVaR": it references class "App\\Entity\\Enfant" but no such service exists.'],
        ], [
            'enfant' => 'App\\Entity\\Enfant',
        ]);
    }
}
