<?php

namespace ContainerXfo08RJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPratiquerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.k1vNbHh.App\Entity\Pratiquer' shared service.
     *
     * @return \App\Entity\Pratiquer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.k1vNbHh": it references class "App\\Entity\\Pratiquer" but no such service exists.');
    }
}
