<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfo08RJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfo08RJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfo08RJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfo08RJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfo08RJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xfo08RJ',
    'container.build_id' => 'a7b7834b',
    'container.build_time' => 1617720037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfo08RJ');
